module: Fix x86 build
We've recently switched from a Ubuntu base image to an Alpine
one. While that fixed the build for RaspberryPi and caused no regression
for aarch64, it makes the build fail on x86 with:

    ./include/uapi/linux/types.h:5:10: fatal error: asm/types.h: No such file or directory

We now install the linux-headers package to fix the above build failure.

Change-type: patch
Signed-off-by: Alexandru Costache <alexandru@balena.io>